insert into flashcards (id, decks_id, question, answer, likes) values (1, 1, 'In sagittis dui vel nisl.', 'scelerisque', 1);
insert into flashcards (id, decks_id, question, answer, likes) values (2, 2, 'Cras pellentesque volutpat dui.', 'posuere metus vitae', 2);
insert into flashcards (id, decks_id, question, answer, likes) values (3, 3, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'ante vivamus tortor', 3);
insert into flashcards (id, decks_id, question, answer, likes) values (4, 4, 'Pellentesque ultrices mattis odio.', 'habitasse platea dictumst', 4);
insert into flashcards (id, decks_id, question, answer, likes) values (5, 5, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 'aliquam erat volutpat', 5);
insert into flashcards (id, decks_id, question, answer, likes) values (6, 6, 'In eleifend quam a odio.', 'arcu sed', 6);
insert into flashcards (id, decks_id, question, answer, likes) values (7, 7, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'luctus', 7);
insert into flashcards (id, decks_id, question, answer, likes) values (8, 8, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'lacinia sapien', 8);
insert into flashcards (id, decks_id, question, answer, likes) values (9, 9, 'Duis consequat dui nec nisi volutpat eleifend.', 'et', 9);
insert into flashcards (id, decks_id, question, answer, likes) values (10, 10, 'In blandit ultrices enim.', 'hendrerit at vulputate', 10);
insert into flashcards (id, decks_id, question, answer, likes) values (11, 11, 'Quisque id justo sit amet sapien dignissim vestibulum.', 'parturient montes', 11);
insert into flashcards (id, decks_id, question, answer, likes) values (12, 12, 'Nulla tempus.', 'posuere cubilia curae', 12);
insert into flashcards (id, decks_id, question, answer, likes) values (13, 13, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'tortor risus dapibus', 13);
insert into flashcards (id, decks_id, question, answer, likes) values (14, 14, 'Donec dapibus.', 'ullamcorper purus sit', 14);
insert into flashcards (id, decks_id, question, answer, likes) values (15, 15, 'Integer non velit.', 'tortor sollicitudin mi', 15);
insert into flashcards (id, decks_id, question, answer, likes) values (16, 16, 'Curabitur at ipsum ac tellus semper interdum.', 'orci luctus', 16);
insert into flashcards (id, decks_id, question, answer, likes) values (17, 17, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'in', 17);
insert into flashcards (id, decks_id, question, answer, likes) values (18, 18, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 'sodales sed tincidunt', 18);
insert into flashcards (id, decks_id, question, answer, likes) values (19, 19, 'Curabitur gravida nisi at nibh.', 'in magna', 19);
insert into flashcards (id, decks_id, question, answer, likes) values (20, 20, 'Nulla tempus.', 'ante ipsum primis', 20);
insert into flashcards (id, decks_id, question, answer, likes) values (21, 21, 'Nullam sit amet turpis elementum ligula vehicula consequat.', 'mattis', 21);
insert into flashcards (id, decks_id, question, answer, likes) values (22, 22, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'odio consequat', 22);
insert into flashcards (id, decks_id, question, answer, likes) values (23, 23, 'Nunc rhoncus dui vel sem.', 'morbi quis', 23);
insert into flashcards (id, decks_id, question, answer, likes) values (24, 24, 'Aliquam erat volutpat.', 'lobortis sapien', 24);
insert into flashcards (id, decks_id, question, answer, likes) values (25, 25, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 'primis in faucibus', 25);
