insert into decks (id, name, users_id, image) values (1, 'Anteater, australian spiny', 1, 'http://dummyimage.com/x100.png/dddddd/000000');
insert into decks (id, name, users_id, image) values (2, 'Oystercatcher, blackish', 2, 'http://dummyimage.com/x100.png/ff4444/ffffff');
insert into decks (id, name, users_id, image) values (3, 'Asiatic jackal', 3, 'http://dummyimage.com/x100.png/dddddd/000000');
insert into decks (id, name, users_id, image) values (4, 'Scottish highland cow', 4, 'http://dummyimage.com/x100.png/ff4444/ffffff');
insert into decks (id, name, users_id, image) values (5, 'Huron', 5, 'http://dummyimage.com/x100.png/cc0000/ffffff');
insert into decks (id, name, users_id, image) values (6, 'Amazon parrot (unidentified)', 6, 'http://dummyimage.com/x100.png/cc0000/ffffff');
insert into decks (id, name, users_id, image) values (7, 'Sarus crane', 7, 'http://dummyimage.com/x100.png/dddddd/000000');
insert into decks (id, name, users_id, image) values (8, 'Large cormorant', 8, 'http://dummyimage.com/x100.png/cc0000/ffffff');
insert into decks (id, name, users_id, image) values (9, 'Puma', 9, 'http://dummyimage.com/x100.png/ff4444/ffffff');
insert into decks (id, name, users_id, image) values (10, 'Red sheep', 10, 'http://dummyimage.com/x100.png/5fa2dd/ffffff');
insert into decks (id, name, users_id, image) values (11, 'Seal, harbor', 11, 'http://dummyimage.com/x100.png/cc0000/ffffff');
insert into decks (id, name, users_id, image) values (12, 'Blue duck', 12, 'http://dummyimage.com/x100.png/cc0000/ffffff');
insert into decks (id, name, users_id, image) values (13, 'Stanley bustard', 13, 'http://dummyimage.com/x100.png/5fa2dd/ffffff');
insert into decks (id, name, users_id, image) values (14, 'Little cormorant', 14, 'http://dummyimage.com/x100.png/dddddd/000000');
insert into decks (id, name, users_id, image) values (15, 'Lily trotter', 15, 'http://dummyimage.com/x100.png/ff4444/ffffff');
insert into decks (id, name, users_id, image) values (16, 'Bahama pintail', 16, 'http://dummyimage.com/x100.png/5fa2dd/ffffff');
insert into decks (id, name, users_id, image) values (17, 'Asian foreset tortoise', 17, 'http://dummyimage.com/x100.png/dddddd/000000');
insert into decks (id, name, users_id, image) values (18, 'Jungle kangaroo', 18, 'http://dummyimage.com/x100.png/5fa2dd/ffffff');
insert into decks (id, name, users_id, image) values (19, 'Marmot, hoary', 19, 'http://dummyimage.com/x100.png/dddddd/000000');
insert into decks (id, name, users_id, image) values (20, 'Southern boubou', 20, 'http://dummyimage.com/x100.png/cc0000/ffffff');
insert into decks (id, name, users_id, image) values (21, 'Polar bear', 21, 'http://dummyimage.com/x100.png/5fa2dd/ffffff');
insert into decks (id, name, users_id, image) values (22, 'Indian jackal', 22, 'http://dummyimage.com/x100.png/cc0000/ffffff');
insert into decks (id, name, users_id, image) values (23, 'Baboon, chacma', 23, 'http://dummyimage.com/x100.png/dddddd/000000');
insert into decks (id, name, users_id, image) values (24, 'Squirrel, uinta ground', 24, 'http://dummyimage.com/x100.png/cc0000/ffffff');
insert into decks (id, name, users_id, image) values (25, 'Stork, white-necked', 25, 'http://dummyimage.com/x100.png/cc0000/ffffff');
