insert into flashcards (id, decks_id, question, answer, likes) values (11, 11, 'In sagittis dui vel nisl.', 'scelerisque', 1);
insert into flashcards (id, decks_id, question, answer, likes) values (12, 12, 'Cras pellentesque volutpat dui.', 'posuere metus vitae', 2);
insert into flashcards (id, decks_id, question, answer, likes) values (13, 13, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'ante vivamus tortor', 3);
insert into flashcards (id, decks_id, question, answer, likes) values (14, 41, 'Pellentesque ultrices mattis odio.', 'habitasse platea dictumst', 4);
insert into flashcards (id, decks_id, question, answer, likes) values (15, 15, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 'aliquam erat volutpat', 5);
insert into flashcards (id, decks_id, question, answer, likes) values (16, 16, 'In eleifend quam a odio.', 'arcu sed', 6);
insert into flashcards (id, decks_id, question, answer, likes) values (17, 17, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'luctus', 7);
insert into flashcards (id, decks_id, question, answer, likes) values (18, 18, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'lacinia sapien', 8);
insert into flashcards (id, decks_id, question, answer, likes) values (19, 19, 'Duis consequat dui nec nisi volutpat eleifend.', 'et', 9);
insert into flashcards (id, decks_id, question, answer, likes) values (110, 110, 'In blandit ultrices enim.', 'hendrerit at vulputate', 10);
insert into flashcards (id, decks_id, question, answer, likes) values (111, 111, 'Quisque id justo sit amet sapien dignissim vestibulum.', 'parturient montes', 11);
insert into flashcards (id, decks_id, question, answer, likes) values (112, 112, 'Nulla tempus.', 'posuere cubilia curae', 12);
insert into flashcards (id, decks_id, question, answer, likes) values (113, 113, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'tortor risus dapibus', 13);
insert into flashcards (id, decks_id, question, answer, likes) values (114, 114, 'Donec dapibus.', 'ullamcorper purus sit', 14);
insert into flashcards (id, decks_id, question, answer, likes) values (115, 115, 'Integer non velit.', 'tortor sollicitudin mi', 15);
insert into flashcards (id, decks_id, question, answer, likes) values (116, 116, 'Curabitur at ipsum ac tellus semper interdum.', 'orci luctus', 16);
insert into flashcards (id, decks_id, question, answer, likes) values (117, 117, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'in', 17);
insert into flashcards (id, decks_id, question, answer, likes) values (118, 118, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 'sodales sed tincidunt', 18);
insert into flashcards (id, decks_id, question, answer, likes) values (119, 119, 'Curabitur gravida nisi at nibh.', 'in magna', 19);
insert into flashcards (id, decks_id, question, answer, likes) values (120, 120, 'Nulla tempus.', 'ante ipsum primis', 20);
insert into flashcards (id, decks_id, question, answer, likes) values (121, 121, 'Nullam sit amet turpis elementum ligula vehicula consequat.', 'mattis', 21);
insert into flashcards (id, decks_id, question, answer, likes) values (122, 122, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'odio consequat', 22);
insert into flashcards (id, decks_id, question, answer, likes) values (123, 123, 'Nunc rhoncus dui vel sem.', 'morbi quis', 23);
insert into flashcards (id, decks_id, question, answer, likes) values (124, 124, 'Aliquam erat volutpat.', 'lobortis sapien', 24);
insert into flashcards (id, decks_id, question, answer, likes) values (125, 125, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 'primis in faucibus', 25);
