insert into flashcards (decks_id, question, answer, likes) values (1, 'benchmark', 'support', 1);
insert into flashcards (decks_id, question, answer, likes) values (2, 'initiative', 'cohesive', 2);
insert into flashcards (decks_id, question, answer, likes) values (3, 'emulation', 'definition', 3);
insert into flashcards (decks_id, question, answer, likes) values (4, 'client-server', 'Synergistic', 4);
insert into flashcards (decks_id, question, answer, likes) values (5, 'interactive', 'throughput', 5);
insert into flashcards (decks_id, question, answer, likes) values (6, 'bandwidth-monitored', 'framework', 6);
insert into flashcards (decks_id, question, answer, likes) values (7, 'firmware', 'Upgradable', 7);
insert into flashcards (decks_id, question, answer, likes) values (8, 'real-time', 'motivating', 8);
insert into flashcards (decks_id, question, answer, likes) values (9, 'Function-based', 'model', 9);
insert into flashcards (decks_id, question, answer, likes) values (10, 'Robust', 'core', 10);
insert into flashcards (decks_id, question, answer, likes) values (11, 'homogeneous', 'model', 11);
insert into flashcards (decks_id, question, answer, likes) values (12, 'Multi-layered', 'disintermediate', 12);
insert into flashcards (decks_id, question, answer, likes) values (13, 'fault-tolerant', 'hierarchy', 13);
insert into flashcards (decks_id, question, answer, likes) values (14, 'Graphic Interface', 'Fundamental', 14);
insert into flashcards (decks_id, question, answer, likes) values (15, 'hub', 'tangible', 15);
insert into flashcards (decks_id, question, answer, likes) values (16, 'access', 'Multi-layered', 16);
insert into flashcards (decks_id, question, answer, likes) values (17, 'real-time', 'Digitized', 17);
insert into flashcards (decks_id, question, answer, likes) values (18, 'moderator', 'homogeneous', 18);
insert into flashcards (decks_id, question, answer, likes) values (19, 'Diverse', 'maximized', 19);
insert into flashcards (decks_id, question, answer, likes) values (20, 'content-based', 'User-centric', 20);
insert into flashcards (decks_id, question, answer, likes) values (21, 'Intuitive', 'cohesive', 21);
insert into flashcards (decks_id, question, answer, likes) values (22, 'Persevering', 'Front-line', 22);
insert into flashcards (decks_id, question, answer, likes) values (23, 'attitude-oriented', 'Public-key', 23);
insert into flashcards (decks_id, question, answer, likes) values (24, 'User-centric', 'intangible', 24);
insert into flashcards (decks_id, question, answer, likes) values (25, 'Fundamental', 'Team-oriented', 25);
insert into flashcards (decks_id, question, answer, likes) values (1, 'What is  9 + 10', '19', 2);
insert into flashcards (decks_id, question, answer, likes) values (1, 'What is the french word for bread', 'Pain', 3);
insert into flashcards (decks_id, question, answer, likes) values (1, 'What do we call our users', 'Nerds', 4);
insert into flashcards (decks_id, question, answer, likes) values (1, 'What part about this bootcamp?', 'Free rubber duck', 5);