insert into tags (id, name, flashcards_id) values (1, 'Crab-eating raccoon', 1);
insert into tags (id, name, flashcards_id) values (2, 'Possum, golden brush-tailed', 2);
insert into tags (id, name, flashcards_id) values (3, 'Jackal, black-backed', 3);
insert into tags (id, name, flashcards_id) values (4, 'Vervet monkey', 4);
insert into tags (id, name, flashcards_id) values (5, 'Skink, blue-tongued', 5);
insert into tags (id, name, flashcards_id) values (6, 'Caracara (unidentified)', 6);
insert into tags (id, name, flashcards_id) values (7, 'Argalis', 7);
insert into tags (id, name, flashcards_id) values (8, 'Galah', 8);
insert into tags (id, name, flashcards_id) values (9, 'Sloth bear', 9);
insert into tags (id, name, flashcards_id) values (10, 'Woodcock, american', 10);
insert into tags (id, name, flashcards_id) values (11, 'Griffon vulture', 11);
insert into tags (id, name, flashcards_id) values (12, 'Swamp deer', 12);
insert into tags (id, name, flashcards_id) values (13, 'Spotted deer', 13);
insert into tags (id, name, flashcards_id) values (14, 'Mongoose, banded', 14);
insert into tags (id, name, flashcards_id) values (15, 'Chameleon (unidentified)', 15);
insert into tags (id, name, flashcards_id) values (16, 'Spotted hyena', 16);
insert into tags (id, name, flashcards_id) values (17, 'Bee-eater (unidentified)', 17);
insert into tags (id, name, flashcards_id) values (18, 'Wombat, southern hairy-nosed', 18);
insert into tags (id, name, flashcards_id) values (19, 'Squirrel, european red', 19);
insert into tags (id, name, flashcards_id) values (20, 'Civet, small-toothed palm', 20);
insert into tags (id, name, flashcards_id) values (21, 'Pheasant, common', 21);
insert into tags (id, name, flashcards_id) values (22, 'Canadian tiger swallowtail butterfly', 22);
insert into tags (id, name, flashcards_id) values (23, 'Prairie falcon', 23);
insert into tags (id, name, flashcards_id) values (24, 'Paca', 24);
insert into tags (id, name, flashcards_id) values (25, 'Baboon, savanna', 25);